# Generated by Django 5.0.6 on 2025-07-04 22:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Payment Confirmed'), ('confirmed', 'Order Confirmed'), ('processing', 'Processing Order'), ('ready_for_dispatch', 'Ready for Dispatch'), ('dispatched', 'Out for Delivery'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending_payment', max_length=30),
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('attempt_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('attempted', 'Delivery Attempted'), ('failed', 'Delivery Failed'), ('rescheduled', 'Delivery Rescheduled'), ('successful', 'Successfully Delivered')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('next_attempt_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_to', models.CharField(blank=True, max_length=100)),
                ('signature', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='orders.order')),
            ],
            options={
                'verbose_name': 'Delivery Attempt',
                'verbose_name_plural': 'Delivery Attempts',
                'db_table': 'delivery_attempts',
                'ordering': ['-attempt_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Payment Confirmed'), ('confirmed', 'Order Confirmed'), ('processing', 'Processing Order'), ('ready_for_dispatch', 'Ready for Dispatch'), ('dispatched', 'Out for Delivery'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=30)),
                ('message', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='orders.order')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Status Update',
                'verbose_name_plural': 'Order Status Updates',
                'db_table': 'order_status_updates',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_for_dispatch_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_company', models.CharField(blank=True, max_length=100)),
                ('dispatch_rider_name', models.CharField(blank=True, max_length=100)),
                ('dispatch_rider_phone', models.CharField(blank=True, max_length=20)),
                ('dispatch_vehicle_info', models.CharField(blank=True, max_length=100)),
                ('in_transit_at', models.DateTimeField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('out_for_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_to', models.CharField(blank=True, max_length=100)),
                ('delivery_signature', models.CharField(blank=True, max_length=100)),
                ('delivery_photo_url', models.URLField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Tracker',
                'verbose_name_plural': 'Order Trackers',
                'db_table': 'order_trackers',
            },
        ),
    ]
