# Generated by Django 5.0.6 on 2025-07-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_deliveryattempt_orderstatusupdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatusupdate',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderstatusupdate',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='ordertracker',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='DeliveryAttempt',
        ),
        migrations.DeleteModel(
            name='OrderStatusUpdate',
        ),
        migrations.DeleteModel(
            name='OrderTracker',
        ),
    ]
