# Generated by Django 5.0.6 on 2025-07-05 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_payment_references(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.filter(payment_reference__isnull=True):
        order.payment_reference = str(uuid.uuid4())
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderstatusupdate_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('gateway_response', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, help_text='Payment channel (card, bank, ussd, etc.)', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('authorization_code', models.CharField(blank=True, max_length=255)),
                ('card_type', models.CharField(blank=True, max_length=50)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('last_4', models.CharField(blank=True, max_length=4)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaystackEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(help_text='Paystack event ID', max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('charge.success', 'Charge Success'), ('charge.failed', 'Charge Failed'), ('invoice.create', 'Invoice Create'), ('invoice.update', 'Invoice Update'), ('subscription.create', 'Subscription Create'), ('subscription.disable', 'Subscription Disable'), ('transfer.success', 'Transfer Success'), ('transfer.failed', 'Transfer Failed'), ('transfer.reversed', 'Transfer Reversed')], max_length=50)),
                ('event_data', models.JSONField(help_text='Complete webhook payload')),
                ('processed', models.BooleanField(default=False)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('last_processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paystack Event',
                'verbose_name_plural': 'Paystack Events',
                'db_table': 'paystack_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(populate_payment_references),
        migrations.AlterField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_access_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Payment Confirmed'), ('confirmed', 'Order Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('failed', 'Payment Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_reference'], name='orders_payment_5a5a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paystack_reference'], name='orders_paystac_976f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_email'], name='orders_custome_cf1fac_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_payment_050188_idx'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='paystackevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paystack_events', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reference'], name='payment_tra_referen_451c50_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['paystack_reference'], name='payment_tra_paystac_bb38a7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='payment_tra_status_137fde_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='payment_tra_created_e43546_idx'),
        ),
        migrations.AddIndex(
            model_name='paystackevent',
            index=models.Index(fields=['event_id'], name='paystack_ev_event_i_7ba673_idx'),
        ),
        migrations.AddIndex(
            model_name='paystackevent',
            index=models.Index(fields=['event_type'], name='paystack_ev_event_t_eac137_idx'),
        ),
        migrations.AddIndex(
            model_name='paystackevent',
            index=models.Index(fields=['processed'], name='paystack_ev_process_e95263_idx'),
        ),
        migrations.AddIndex(
            model_name='paystackevent',
            index=models.Index(fields=['created_at'], name='paystack_ev_created_2b3e9c_idx'),
        ),
    ]
