# Generated by Django 5.0.6 on 2025-08-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_payment_reference'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payment_tra_created_e43546_idx',
        ),
        migrations.RemoveIndex(
            model_name='paystackevent',
            name='paystack_ev_created_2b3e9c_idx',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='authorization_code',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='last_4',
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earned', 'Points Earned'), ('used', 'Points Used'), ('expired', 'Points Expired'), ('bonus', 'Bonus Points'), ('reversal', 'Points Reversal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='channel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paystackevent',
            name='event_type',
            field=models.CharField(choices=[('charge.success', 'Charge Success'), ('charge.failed', 'Charge Failed')], max_length=50),
        ),
    ]
