# Generated by Django 5.0.6 on 2025-09-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_best_seller_product_is_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCollection',
            fields=[
                ('collection_type', models.CharField(choices=[('new', 'New Arrivals'), ('popular', 'Popular Picks'), ('best_seller', 'Best Sellers')], max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'New Arrivals'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_product', models.ForeignKey(blank=True, help_text='The product whose image will be used as the collection background.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageFeaturedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_slot_1', to='products.product')),
                ('product2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_slot_2', to='products.product')),
                ('product3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_slot_3', to='products.product')),
                ('product4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_slot_4', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Home Page Featured Products',
            },
        ),
    ]
